import {loadState,saveState,statusLabel} from '../core/fleet-state.js';
import {initCommon} from '../layout/common.js';
initCommon();
let s=loadState();
let selectedCharger=null;
const priorityRank={critical:0,high:1,normal:2,low:3};
const toast=document.getElementById('depot-toast');
const drawer=document.getElementById('charger-drawer');
const backdrop=document.getElementById('charger-drawer-backdrop');
const dialog=document.getElementById('charger-dialog');
const search=document.getElementById('charger-search');
const statusFilter=document.getElementById('charger-status-filter');
const typeFilter=document.getElementById('charger-type-filter');
const chargerDefaults={
  'DC-01':{manufacturer:'ABB',model:'Terra 184',serial:'ABB-T184-24091',firmware:'7.14.2',temperature:41,uptime:99.6,connectors:[{id:'1',type:'CCS2',power:150,status:'busy'},{id:'2',type:'CCS2',power:150,status:'available'}]},
  'DC-02':{manufacturer:'ABB',model:'Terra 184',serial:'ABB-T184-24092',firmware:'7.14.2',temperature:36,uptime:99.9,connectors:[{id:'1',type:'CCS2',power:150,status:'available'},{id:'2',type:'CCS2',power:150,status:'available'}]},
  'DC-03':{manufacturer:'Siemens',model:'Sicharge D',serial:'SIE-SD-11804',firmware:'3.8.6',temperature:43,uptime:98.8,connectors:[{id:'1',type:'CCS2',power:120,status:'busy'}]},
  'DC-04':{manufacturer:'Siemens',model:'Sicharge D',serial:'SIE-SD-11805',firmware:'3.8.4',temperature:58,uptime:94.1,connectors:[{id:'1',type:'CCS2',power:120,status:'busy'}]},
  'AC-05':{manufacturer:'Wallbox',model:'Commander 2',serial:'WB-C2-55103',firmware:'6.2.1',temperature:31,uptime:99.9,connectors:[{id:'1',type:'Type 2',power:22,status:'available'}]},
  'AC-06':{manufacturer:'Wallbox',model:'Commander 2',serial:'WB-C2-55104',firmware:'6.1.8',temperature:49,uptime:87.4,fault:'Connector communication error',connectors:[{id:'1',type:'Type 2',power:22,status:'faulty'}]},
  'AC-07':{manufacturer:'Wallbox',model:'Commander 2',serial:'WB-C2-55105',firmware:'6.2.1',temperature:34,uptime:99.2,connectors:[{id:'1',type:'Type 2',power:22,status:'busy'}]},
  'AC-08':{manufacturer:'Wallbox',model:'Commander 2',serial:'WB-C2-55106',firmware:'6.2.1',temperature:30,uptime:99.7,connectors:[{id:'1',type:'Type 2',power:22,status:'reserved'}]}
};
function enrich(c){return {...chargerDefaults[c.id],...c,connectors:(c.connectors||chargerDefaults[c.id]?.connectors||[])};}
function notify(message,type='success'){if(!toast)return;toast.textContent=message;toast.className=`inline-toast is-visible inline-toast--${type}`;clearTimeout(notify.timer);notify.timer=setTimeout(()=>toast.className='inline-toast',2800);}
function queuedVehicles(){return s.vehicles.filter(v=>v.status==='queued').sort((a,b)=>priorityRank[a.priority]-priorityRank[b.priority]||a.departure.localeCompare(b.departure));}
function availableChargers(){return s.chargers.filter(c=>c.status==='available').sort((a,b)=>b.power-a.power);}
function activeSessionFor(c){return (s.sessions||[]).find(x=>x.charger===c.id&&x.status==='active');}
function save(){saveState(s);}
function assignVehicle(vehicleId,chargerId){
  const vehicle=s.vehicles.find(v=>v.id===vehicleId),charger=s.chargers.find(c=>c.id===chargerId);
  if(!vehicle||!charger||charger.status!=='available'){notify('Selected charger is no longer available.','error');return;}
  vehicle.status='charging';vehicle.charger=charger.id;vehicle.power=Math.min(charger.power,vehicle.priority==='critical'?120:90);
  charger.status='busy';charger.vehicle=vehicle.id;
  s.energy.currentKw=Math.min(s.energy.capacityKw,s.vehicles.filter(v=>v.status==='charging').reduce((a,v)=>a+v.power,0)+86);
  save();selectedCharger=charger.id;render();openDrawer(charger.id);notify(`${vehicle.id} assigned to ${charger.id}.`);
}
function filteredChargers(){
  const q=(search?.value||'').trim().toLowerCase(),st=statusFilter?.value||'all',tp=typeFilter?.value||'all';
  return s.chargers.map(enrich).filter(c=>{
    const v=c.vehicle?s.vehicles.find(x=>x.id===c.vehicle):null;
    const hay=[c.id,c.bay,c.manufacturer,c.model,c.serial,c.vehicle,v?.name].join(' ').toLowerCase();
    return (!q||hay.includes(q))&&(st==='all'||c.status===st)&&(tp==='all'||c.type===tp);
  });
}
function bayStatus(c){if(c.status==='busy')return 'occupied';if(c.status==='reserved')return 'reserved';if(['faulty','maintenance','offline'].includes(c.status))return 'blocked';return 'available';}
function render(){
  const chargers=s.chargers.map(enrich),busy=chargers.filter(c=>c.status==='busy').length,avail=chargers.filter(c=>c.status==='available').length,faulty=chargers.filter(c=>['faulty','maintenance','offline'].includes(c.status)).length,res=chargers.filter(c=>c.status==='reserved').length;
  const avgHealth=Math.round(chargers.reduce((a,c)=>a+(c.health||0),0)/Math.max(chargers.length,1));
  document.getElementById('depot-kpis').innerHTML=[['Chargers online',chargers.length-faulty,`${chargers.length} installed`],['Available now',avail,`${busy} actively charging`],['Infrastructure health',`${avgHealth}%`,faulty?`${faulty} need attention`:'All systems healthy'],['Depot power',`${s.energy.currentKw} kW`,`${Math.max(0,s.energy.capacityKw-s.energy.currentKw)} kW headroom`]].map(x=>`<article class="kpi-card"><span>${x[0]}</span><strong>${x[1]}</strong><small>${x[2]}</small></article>`).join('');
  document.getElementById('charger-availability-chip').textContent=`${avail} available`;
  const list=filteredChargers();document.getElementById('charger-results-count').textContent=`${list.length} of ${chargers.length} chargers`;
  document.getElementById('charger-grid').innerHTML=list.length?list.map(c=>{const session=activeSessionFor(c),v=c.vehicle?s.vehicles.find(x=>x.id===c.vehicle):null;return `<button class="charger-card charger-card--button charger-card--v2" data-charger="${c.id}" type="button"><div class="charger-card__top"><div><strong>${c.id}</strong><span class="charger-model">${c.manufacturer} · ${c.model}</span></div><span class="ui-pill status-pill status-${c.status}">${statusLabel(c.status)}</span></div><div class="charger-power-row"><h3>${c.power} kW</h3><span>${c.type}</span></div><p>Bay ${c.bay} · ${c.connectors.length} connector${c.connectors.length===1?'':'s'}</p><div class="charger-live-row"><span>${v?`${v.id} · ${v.battery}% SOC`:'No vehicle assigned'}</span><strong>${session?`${session.power} kW live`:c.status==='available'?'Ready':'—'}</strong></div><div class="health"><div class="health__label"><span>Health</span><strong>${c.health}%</strong></div><div class="progress"><span class="${c.health<70?'bar-danger':c.health<90?'bar-warning':''}" style="width:${c.health}%"></span></div></div></button>`}).join(''):'<div class="empty-state empty-state--panel">No chargers match these filters.</div>';
  document.querySelectorAll('[data-charger]').forEach(el=>el.onclick=()=>openDrawer(el.dataset.charger));
  const queue=queuedVehicles();document.getElementById('queue-count').textContent=`${queue.length} waiting`;
  document.getElementById('vehicle-queue').innerHTML=queue.length?queue.map(v=>`<div class="queue-row"><div class="ui-pill queue-priority priority-${v.priority}">${v.priority}</div><div class="queue-main"><strong>${v.id} · ${v.name}</strong><span>${v.route} · departs ${v.departure}</span></div><div class="queue-energy"><strong>${v.requiredKwh} kWh</strong><span>${v.battery}% → ${v.target}%</span></div><select class="queue-charger-select" data-select-for="${v.id}" aria-label="Charger for ${v.id}"><option value="">Select charger</option>${availableChargers().map(c=>`<option value="${c.id}">${c.id} · ${c.power} kW</option>`).join('')}</select><button class="action-button" data-assign-vehicle="${v.id}" type="button">Assign</button></div>`).join(''):'<div class="empty-state empty-state--panel">No vehicles are waiting for a charger.</div>';
  document.querySelectorAll('[data-assign-vehicle]').forEach(btn=>btn.onclick=()=>{const id=btn.dataset.assignVehicle,sel=document.querySelector(`[data-select-for="${id}"]`);if(!sel?.value)return notify('Select an available charger first.','warning');assignVehicle(id,sel.value)});
  const bays=chargers.map(c=>({id:c.bay,status:bayStatus(c),charger:c.id,vehicle:c.vehicle}));document.getElementById('bay-count-chip').textContent=`${bays.filter(b=>b.status==='available').length} free`;
  document.getElementById('parking-bay-grid').innerHTML=bays.map(b=>`<button class="bay-card bay-card--${b.status}" data-bay-charger="${b.charger}" type="button"><div><strong>${b.id}</strong><span>${b.status}</span></div><small>${b.charger}${b.vehicle?` · ${b.vehicle}`:''}</small></button>`).join('');
  document.querySelectorAll('[data-bay-charger]').forEach(btn=>btn.onclick=()=>openDrawer(btn.dataset.bayCharger));
  document.getElementById('depot-rail-stack').innerHTML=`<div class="depot-rail-card"><span>Bay utilization</span><strong>${Math.round((busy+res)/Math.max(chargers.length,1)*100)}%</strong><small>${busy+res} occupied or reserved</small></div><div class="depot-rail-card"><span>Service attention</span><strong>${faulty}</strong><small>${faulty?'Faulty / offline chargers':'No active faults'}</small></div><div class="depot-rail-card"><span>Avg. uptime</span><strong>${(chargers.reduce((a,c)=>a+(c.uptime||100),0)/chargers.length).toFixed(1)}%</strong><small>Across installed chargers</small></div><div class="depot-rail-card"><span>Queue pressure</span><strong>${queue.length}</strong><small>${avail?`${avail} charger${avail===1?'':'s'} can accept vehicles`:'No charger available'}</small></div>`;
  const p=Math.round(s.energy.currentKw/s.energy.capacityKw*100),headroom=Math.max(0,s.energy.capacityKw-s.energy.currentKw);document.getElementById('depot-load').textContent=`${s.energy.currentKw} / ${s.energy.capacityKw} kW`;document.getElementById('depot-load-pct').textContent=`${p}%`;document.getElementById('depot-load-bar').style.width=`${p}%`;document.getElementById('capacity-scale').textContent=`${s.energy.capacityKw} kW capacity`;document.getElementById('headroom-chip').textContent=`${headroom} kW headroom`;
  const charging=s.vehicles.filter(v=>v.status==='charging').sort((a,b)=>priorityRank[a.priority]-priorityRank[b.priority]||a.departure.localeCompare(b.departure));document.getElementById('depot-allocation').innerHTML=charging.map(v=>`<div class="allocation-row"><div class="allocation-row__head"><div><strong>${v.id} · ${v.name}</strong><span>${v.charger} · departs ${v.departure} · ${v.priority}</span></div><strong>${v.power} kW</strong></div><div class="allocation-bar"><span style="width:${Math.round(v.power/Math.max(s.energy.capacityKw,1)*100)}%"></span></div></div>`).join('')||'<div class="empty-state">No active charging sessions.</div>';
  const grid=Math.max(0,s.energy.currentKw-s.energy.solarKw);document.getElementById('energy-sources').innerHTML=`<div class="energy-source"><span>Grid draw</span><strong>${grid} kW</strong><small>Main supply</small></div><div class="energy-source"><span>Solar</span><strong>${s.energy.solarKw} kW</strong><small>On-site generation</small></div><div class="energy-source"><span>Site battery</span><strong>${s.energy.siteBatteryPct}%</strong><small>State of charge</small></div><div class="energy-source"><span>Energy price</span><strong>${s.energy.priceAmd}</strong><small>AMD / kWh</small></div>`;
  document.getElementById('smart-priority').checked=s.settings.smartPriority;document.getElementById('peak-protection').checked=s.settings.peakProtection;
}
function connectorMarkup(c){return c.connectors.map(x=>`<div class="connector-row"><div class="connector-icon">ϟ</div><div><strong>Connector ${x.id} · ${x.type}</strong><span>Up to ${x.power} kW</span></div><span class="ui-pill status-pill status-${x.status}">${statusLabel(x.status)}</span></div>`).join('');}
function openDrawer(id){selectedCharger=id;const c=enrich(s.chargers.find(x=>x.id===id));if(!c)return;const v=c.vehicle?s.vehicles.find(x=>x.id===c.vehicle):null,session=activeSessionFor(c);document.getElementById('charger-drawer-title').textContent=c.id;document.getElementById('charger-drawer-subtitle').textContent=`${c.manufacturer} ${c.model} · Bay ${c.bay}`;document.getElementById('charger-drawer-body').innerHTML=`<div class="charger-detail-hero"><div><span>Maximum output</span><strong>${c.power} kW</strong><small>${c.type} fast charging</small></div><span class="ui-pill status-pill status-${c.status}">${statusLabel(c.status)}</span></div><div class="ui-detail-section"><h3>Hardware & health</h3><div class="ui-detail-grid"><div><span>Health</span><strong>${c.health}%</strong></div><div><span>Uptime</span><strong>${c.uptime}%</strong></div><div><span>Temperature</span><strong class="${c.temperature>=55?'text-warning':''}">${c.temperature}°C</strong></div><div><span>Firmware</span><strong>${c.firmware}</strong></div></div><div class="ui-detail-list"><div><span>Serial number</span><strong>${c.serial}</strong></div><div><span>Manufacturer</span><strong>${c.manufacturer}</strong></div><div><span>Model</span><strong>${c.model}</strong></div>${c.fault?`<div><span>Active fault</span><strong class="text-warning">${c.fault}</strong></div>`:''}</div></div><div class="ui-detail-section"><h3>Connectors</h3><div class="connector-list">${connectorMarkup(c)}</div></div><div class="ui-detail-section"><h3>Current assignment</h3>${v?`<div class="charger-assignment-card"><strong>${v.id} · ${v.name}</strong><span>${v.battery}% → ${v.target}% · departs ${v.departure}</span>${session?`<div><b>${session.power} kW</b><b>${session.energy} kWh</b><b>${session.duration}</b></div>`:''}</div>`:'<div class="empty-state">No vehicle assigned.</div>'}</div>`;document.getElementById('charger-secondary-action').textContent=c.status==='available'?'Reserve charger':'View session';document.getElementById('charger-primary-action').textContent=c.status==='faulty'?'Recovery actions':'Manage charger';backdrop.hidden=false;requestAnimationFrame(()=>{backdrop.classList.add('is-visible');drawer.classList.add('is-open')});drawer.setAttribute('aria-hidden','false');}
function closeDrawer(){drawer.classList.remove('is-open');backdrop.classList.remove('is-visible');drawer.setAttribute('aria-hidden','true');setTimeout(()=>backdrop.hidden=true,180);}
function openManageDialog(){const c=enrich(s.chargers.find(x=>x.id===selectedCharger));if(!c)return;document.getElementById('charger-dialog-title').textContent=`Manage ${c.id}`;document.getElementById('charger-dialog-subtitle').textContent=`${c.manufacturer} ${c.model} · Bay ${c.bay}`;document.getElementById('charger-dialog-body').innerHTML=`<div class="charger-action-grid"><label class="ops-choice"><input type="radio" name="charger-action" value="restart" checked><strong>Restart charger</strong><span>Simulate a safe remote reboot.</span></label><label class="ops-choice"><input type="radio" name="charger-action" value="maintenance"><strong>Set maintenance</strong><span>Block charger from new assignments.</span></label><label class="ops-choice"><input type="radio" name="charger-action" value="disable"><strong>Disable charger</strong><span>Take charger offline for operations.</span></label><label class="ops-choice"><input type="radio" name="charger-action" value="restore"><strong>Restore availability</strong><span>Return charger to available state.</span></label></div>`;dialog.showModal();}
function applyManageAction(){const c=s.chargers.find(x=>x.id===selectedCharger),action=document.querySelector('input[name="charger-action"]:checked')?.value;if(!c||!action)return;if(action==='restart'){notify(`${c.id} restart command completed.`);c.health=Math.min(100,(c.health||90)+2);}else if(action==='maintenance'){c.status='maintenance';c.vehicle=null;notify(`${c.id} moved to maintenance.`,'warning');}else if(action==='disable'){c.status='offline';c.vehicle=null;notify(`${c.id} disabled.`,'warning');}else if(action==='restore'){c.status='available';c.vehicle=null;c.health=Math.max(c.health||0,90);notify(`${c.id} restored to available.`);}save();render();openDrawer(c.id);}
[search,statusFilter,typeFilter].forEach(el=>el?.addEventListener(el===search?'input':'change',render));document.getElementById('charger-drawer-close').onclick=closeDrawer;backdrop.onclick=closeDrawer;document.getElementById('charger-primary-action').onclick=openManageDialog;document.getElementById('charger-secondary-action').onclick=()=>{const c=s.chargers.find(x=>x.id===selectedCharger);if(!c)return;if(c.status==='available'){c.status='reserved';save();render();openDrawer(c.id);notify(`${c.id} reserved for fleet operations.`);}else{location.href='./sessions.html';}};document.getElementById('charger-dialog-form').addEventListener('submit',e=>{if(e.submitter?.id==='charger-dialog-confirm')applyManageAction();});document.getElementById('smart-priority').onchange=e=>{s.settings.smartPriority=e.target.checked;save();notify(`Smart priority ${e.target.checked?'enabled':'disabled'}.`)};document.getElementById('peak-protection').onchange=e=>{s.settings.peakProtection=e.target.checked;save();notify(`Peak protection ${e.target.checked?'enabled':'disabled'}.`)};document.getElementById('rebalance-button').onclick=()=>{const charging=s.vehicles.filter(v=>v.status==='charging').sort((a,b)=>priorityRank[a.priority]-priorityRank[b.priority]||a.departure.localeCompare(b.departure));let remaining=Math.min(s.energy.capacityKw-86,480);charging.forEach(v=>{const preferred=v.priority==='critical'?140:v.priority==='high'?110:80;v.power=Math.max(22,Math.min(preferred,remaining));remaining=Math.max(0,remaining-v.power)});s.energy.currentKw=charging.reduce((a,v)=>a+v.power,0)+86;save();render();notify('Power allocation rebalanced by departure priority.');};document.getElementById('assign-button').onclick=()=>{const vehicle=queuedVehicles()[0],charger=availableChargers()[0];if(!vehicle||!charger)return notify('No queued vehicle or available charger.','warning');assignVehicle(vehicle.id,charger.id);};
render();
const requestedCharger=new URLSearchParams(location.search).get('charger');
if(requestedCharger&&s.chargers.some(c=>c.id===requestedCharger))openDrawer(requestedCharger);
