import {loadState,saveState} from '../core/fleet-state.js';
import {initCommon} from '../layout/common.js';
initCommon();
let s=loadState();
let activeId=null,editId=null,toastTimer=null;
const $=id=>document.getElementById(id);
const els={rows:$('driver-rows'),q:$('driver-search'),status:$('driver-status'),department:$('driver-department'),access:$('driver-access'),drawer:$('driver-drawer'),backdrop:$('driver-drawer-backdrop'),body:$('driver-drawer-body'),form:$('driver-form-dialog'),assign:$('driver-assign-dialog'),toast:$('driver-toast')};
const defaults=(d,i)=>({employeeId:`EMP-${String(i+1).padStart(4,'0')}`,email:`${d.name.toLowerCase().replace(/[^a-z]+/g,'.').replace(/^\.|\.$/g,'')}@araratmobility.am`,rfid:d.access?.includes('RFID')?`RFID-${String(1001+i)}`:'—',homeCharging:i%3!==0?'eligible':'not-eligible',...d});
function normalize(){s.drivers=s.drivers.map(defaults);saveState(s)}
normalize();
function vehicle(id){return s.vehicles.find(v=>v.id===id)}
function nextSchedule(d){return s.schedules.filter(x=>(x.driver===d.id)||(!x.driver&&x.vehicle===d.vehicle)).sort((a,b)=>a.departure.localeCompare(b.departure))[0]||null}
function statusText(v){return v==='attention'?'Needs attention':v[0].toUpperCase()+v.slice(1)}
function populateDepartments(){const current=els.department.value||'all';const vals=[...new Set(s.drivers.map(d=>d.department).filter(Boolean))].sort();els.department.innerHTML='<option value="all">All departments</option>'+vals.map(v=>`<option value="${v}">${v}</option>`).join('');els.department.value=vals.includes(current)?current:'all'}
function matchesAccess(d,f){if(f==='all')return true;if(f==='blocked')return d.status==='suspended';if(f==='rfid')return d.access.includes('RFID');return !d.access.includes('RFID')&&d.access.toLowerCase().includes('app')}
function render(){populateDepartments();const q=els.q.value.trim().toLowerCase();let data=s.drivers.filter(d=>{const v=vehicle(d.vehicle),sch=nextSchedule(d);const hay=[d.name,d.employeeId,d.department,d.vehicle,v?.name,d.phone,d.email,sch?.route].join(' ').toLowerCase();return (!q||hay.includes(q))&&(els.status.value==='all'||d.status===els.status.value)&&(els.department.value==='all'||d.department===els.department.value)&&matchesAccess(d,els.access.value)});$('driver-total').textContent=s.drivers.length;$('driver-active').textContent=s.drivers.filter(d=>d.status==='active').length;$('driver-assigned').textContent=s.drivers.filter(d=>vehicle(d.vehicle)).length;$('driver-attention').textContent=s.drivers.filter(d=>d.status!=='active'||!vehicle(d.vehicle)||(!d.access.includes('RFID')&&d.rfid&&d.rfid!=='—')).length;$('driver-visible-count').textContent=`${data.length} visible`;els.rows.innerHTML=data.map(d=>{const v=vehicle(d.vehicle),sch=nextSchedule(d);return `<tr data-driver-row="${d.id}"><td><div class="driver-identity"><span class="ui-avatar">${d.name.split(' ').map(x=>x[0]).slice(0,2).join('')}</span><div><strong>${d.name}</strong><span>${d.employeeId} · ${d.phone}</span></div></div></td><td><div class="entity-main"><strong>${d.department}</strong><span>${d.shift}</span></div></td><td><div class="entity-main"><strong>${v?v.id:'Unassigned'}</strong><span>${v?v.name:'No vehicle'}</span></div></td><td><div class="entity-main"><strong>${sch?sch.departure:'—'}</strong><span>${sch?sch.route:'No scheduled route'}</span></div></td><td><div class="driver-access-cell"><strong>${d.access}</strong><span>${d.rfid&&d.rfid!=='—'?d.rfid:'No RFID card'}</span></div></td><td><span class="ui-pill status-pill ${d.homeCharging==='eligible'?'status-active':'priority-low'}">${d.homeCharging==='eligible'?'Eligible':'Not eligible'}</span></td><td><span class="ui-pill status-pill status-${d.status}">${statusText(d.status)}</span></td><td><button class="ui-row-menu" type="button" data-open-driver="${d.id}">•••</button></td></tr>`}).join('')||'<tr><td colspan="8"><div class="ops-empty">No drivers match these filters.</div></td></tr>';document.querySelectorAll('[data-open-driver]').forEach(b=>b.onclick=e=>{e.stopPropagation();openDrawer(b.dataset.openDriver)});document.querySelectorAll('[data-driver-row]').forEach(r=>r.ondblclick=()=>openDrawer(r.dataset.driverRow))}
function openDrawer(id){const d=s.drivers.find(x=>x.id===id);if(!d)return;activeId=id;const v=vehicle(d.vehicle),sch=nextSchedule(d),claims=s.reimbursements.filter(x=>x.driver===d.id),energy=claims.reduce((a,x)=>a+x.energy,0),amount=claims.reduce((a,x)=>a+x.amount,0);$('driver-drawer-title').textContent=d.name;$('driver-drawer-subtitle').textContent=`${d.employeeId} · ${d.department}`;els.body.innerHTML=`${d.status!=='active'?`<div class="ui-callout ui-callout--warning"><strong>${statusText(d.status)}</strong><span>Review account access or vehicle assignment before the next shift.</span></div>`:''}<section class="driver-profile-hero"><span class="ui-avatar ui-avatar--large">${d.name.split(' ').map(x=>x[0]).slice(0,2).join('')}</span><div><strong>${d.name}</strong><span>${d.employeeId}</span><small>${d.department} · ${d.shift}</small></div><span class="ui-pill status-pill status-${d.status}">${statusText(d.status)}</span></section><section class="ui-detail-section"><h3>Contact & employment</h3><div class="ui-detail-grid"><div><span>Phone</span><strong>${d.phone}</strong></div><div><span>Email</span><strong>${d.email}</strong></div><div><span>Department</span><strong>${d.department}</strong></div><div><span>Shift</span><strong>${d.shift}</strong></div></div></section><section class="ui-detail-section"><h3>Vehicle & departure</h3><div class="ui-detail-list"><div><span>Assigned vehicle</span><strong>${v?`${v.id} · ${v.name}`:'Unassigned'}</strong></div><div><span>Next departure</span><strong>${sch?`${sch.departure} · ${sch.route}`:'No schedule'}</strong></div><div><span>Required SOC</span><strong>${sch?`${sch.target}%`:'—'}</strong></div><div><span>Vehicle SOC</span><strong>${v?`${v.battery}%`:'—'}</strong></div></div></section><section class="ui-detail-section"><h3>Access & authentication</h3><div class="ui-detail-list"><div><span>Access method</span><strong>${d.access}</strong></div><div><span>RFID card</span><strong>${d.rfid||'—'}</strong></div><div><span>Fleet account</span><strong>${d.status==='suspended'?'Blocked':'Enabled'}</strong></div></div></section><section class="ui-detail-section"><h3>Home charging</h3><div class="ui-detail-grid"><div><span>Eligibility</span><strong>${d.homeCharging==='eligible'?'Eligible':'Not eligible'}</strong></div><div><span>Claims</span><strong>${claims.length}</strong></div><div><span>Energy reimbursed</span><strong>${energy.toFixed(1)} kWh</strong></div><div><span>Claim value</span><strong>${Math.round(amount).toLocaleString()} AMD</strong></div></div></section>`;$('driver-status-action').textContent=d.status==='suspended'?'Reactivate driver':'Suspend driver';els.backdrop.hidden=false;requestAnimationFrame(()=>els.backdrop.classList.add('is-visible'));els.drawer.classList.add('is-open');els.drawer.setAttribute('aria-hidden','false')}
function closeDrawer(){els.drawer.classList.remove('is-open');els.drawer.setAttribute('aria-hidden','true');els.backdrop.classList.remove('is-visible');setTimeout(()=>els.backdrop.hidden=true,180)}
function openForm(id=null){editId=id;const d=id?s.drivers.find(x=>x.id===id):null;$('driver-form-title').textContent=d?'Edit driver':'Add driver';$('driver-form-name').value=d?.name||'';$('driver-form-employee').value=d?.employeeId||`EMP-${String(s.drivers.length+1).padStart(4,'0')}`;$('driver-form-phone').value=d?.phone||'';$('driver-form-email').value=d?.email||'';$('driver-form-department').value=d?.department||'';$('driver-form-shift').value=d?.shift||'08:00–16:00';$('driver-form-access').value=d?.access||'Driver app';$('driver-form-rfid').value=d?.rfid==='—'?'':(d?.rfid||'');$('driver-form-home').value=d?.homeCharging||'eligible';$('driver-form-status').value=d?.status||'active';els.form.showModal()}
function saveDriver(){const data={name:$('driver-form-name').value.trim(),employeeId:$('driver-form-employee').value.trim(),phone:$('driver-form-phone').value.trim(),email:$('driver-form-email').value.trim()||'—',department:$('driver-form-department').value.trim(),shift:$('driver-form-shift').value.trim(),access:$('driver-form-access').value,rfid:$('driver-form-rfid').value.trim()||'—',homeCharging:$('driver-form-home').value,status:$('driver-form-status').value};if(editId){Object.assign(s.drivers.find(x=>x.id===editId),data)}else{const n=Math.max(0,...s.drivers.map(d=>Number((d.id.match(/\d+/)||['0'])[0])))+1;s.drivers.push({id:`DR-${String(n).padStart(2,'0')}`,vehicle:'',...data})}saveState(s);render();if(editId===activeId)openDrawer(activeId);toast(editId?'Driver updated':'Driver added')}
function openAssign(){const d=s.drivers.find(x=>x.id===activeId);if(!d)return;$('driver-assign-subtitle').textContent=`Assign a vehicle to ${d.name}.`;$('driver-assign-vehicle').innerHTML='<option value="">Unassigned</option>'+s.vehicles.map(v=>`<option value="${v.id}" ${d.vehicle===v.id?'selected':''}>${v.id} · ${v.name}</option>`).join('');els.assign.showModal()}
function saveAssignment(){const d=s.drivers.find(x=>x.id===activeId);if(!d)return;const newId=$('driver-assign-vehicle').value;s.drivers.forEach(x=>{if(x.id!==d.id&&x.vehicle===newId)x.vehicle='' });d.vehicle=newId;if(newId){const v=vehicle(newId);if(v){v.route=nextSchedule(d)?.route||v.route;v.departure=nextSchedule(d)?.departure||v.departure}}s.schedules.forEach(x=>{if(!x.driver&&x.vehicle===newId)x.driver=d.id});saveState(s);render();openDrawer(d.id);toast('Vehicle assignment updated')}
function toggleStatus(){const d=s.drivers.find(x=>x.id===activeId);if(!d)return;d.status=d.status==='suspended'?'active':'suspended';saveState(s);render();openDrawer(d.id);toast(d.status==='suspended'?'Driver suspended':'Driver reactivated')}
function toast(msg){clearTimeout(toastTimer);els.toast.textContent=msg;els.toast.classList.add('is-visible');toastTimer=setTimeout(()=>els.toast.classList.remove('is-visible'),2200)}
[els.q,els.status,els.department,els.access].forEach(el=>el.addEventListener('input',render));$('driver-add').onclick=()=>openForm();$('driver-reset').onclick=()=>{localStorage.removeItem('voltdrive_fleet_manager_v1');s=loadState();normalize();render();toast('Demo data restored')};$('driver-drawer-close').onclick=closeDrawer;els.backdrop.onclick=closeDrawer;$('driver-edit').onclick=()=>openForm(activeId);$('driver-assign').onclick=openAssign;$('driver-status-action').onclick=toggleStatus;$('driver-form').addEventListener('submit',e=>{if(e.submitter?.value==='cancel')return;if(!$('driver-form-name').value.trim()||!$('driver-form-employee').value.trim()){e.preventDefault();return}saveDriver()});$('driver-assign-form').addEventListener('submit',e=>{if(e.submitter?.value==='cancel')return;saveAssignment()});render();const driverParam=new URLSearchParams(location.search).get('driver');if(driverParam)openDrawer(driverParam);
