import {loadState,statusLabel,departmentName,parkingBayCode} from '../core/fleet-state.js';
import {initCommon} from '../layout/common.js';
import {buildFleetReport,chargerReportStats,parkingBayReportStats,durationMinutes} from '../core/reporting.js';

const access=initCommon();
if(!access.denied){
const s=loadState();
const $=id=>document.getElementById(id);
const nf=new Intl.NumberFormat('en-US');
const df=new Intl.NumberFormat('en-US',{maximumFractionDigits:1});
const money=n=>`${nf.format(Math.round(Number(n)||0))} AMD`;
const num=(n,d=0)=>d===1?df.format(Number(n)||0):nf.format(Math.round(Number(n)||0));
const pct=n=>`${num(n,1)}%`;
const esc=value=>String(value??'').replace(/[&<>'"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[c]));
const MAX_RENDER_ROWS=250;
const els={period:$('report-period'),department:$('report-department'),vehicle:$('report-vehicle'),driver:$('report-driver'),charger:$('report-charger'),vehicleRows:$('report-vehicle-rows'),chargerRows:$('report-charger-rows'),scheduleRows:$('report-schedule-rows'),drawer:$('report-drawer'),backdrop:$('report-drawer-backdrop'),toast:$('report-toast')};
const vehicles=s.vehicles||[],drivers=s.drivers||[],chargers=s.chargers||[],departments=s.departments||[],parkingBays=s.parkingBays||[];
const vehicleById=new Map(vehicles.map(v=>[v.id,v]));
const driverById=new Map(drivers.map(d=>[d.id,d]));
const driverByVehicle=new Map();drivers.forEach(d=>{if(d.vehicle&&!driverByVehicle.has(d.vehicle))driverByVehicle.set(d.vehicle,d)});
let trendMode='energy',drawerEntity=null,renderQueued=false,renderBusy=false;
function driverForVehicle(id){return driverByVehicle.get(id)||null}
function departmentForVehicle(id){const v=vehicleById.get(id),d=driverForVehicle(id);return departmentName(s,v?.departmentId||d?.departmentId)||'Unassigned'}
function filters(){return {period:els.period?.value||'week',departmentId:els.department?.value||'all',vehicleId:els.vehicle?.value||'all',driverId:els.driver?.value||'all',chargerId:els.charger?.value||'all'}}
function report(){return buildFleetReport(s,filters())}
function formatDate(key){if(!key)return '—';const d=new Date(`${key}T00:00:00Z`);return Number.isNaN(d.getTime())?key:d.toLocaleDateString('en-US',{month:'short',day:'numeric',year:'numeric',timeZone:'UTC'})}
function timeSlot(slot){if(!slot)return '—';return `${String(slot.start).padStart(2,'0')}:00–${String((slot.start+2)%24).padStart(2,'0')}:00`}
function populateFilters(){
  if(els.department)els.department.innerHTML='<option value="all">All departments</option>'+departments.filter(d=>d.status!=='inactive').map(d=>`<option value="${esc(d.id)}">${esc(d.name)}</option>`).join('');
  if(els.vehicle)els.vehicle.innerHTML='<option value="all">All vehicles</option>'+vehicles.filter(v=>v.active!==false).map(v=>`<option value="${esc(v.id)}">${esc(v.id)} · ${esc(v.name)}</option>`).join('');
  if(els.driver)els.driver.innerHTML='<option value="all">All drivers</option>'+drivers.map(d=>`<option value="${esc(d.id)}">${esc(d.name)}</option>`).join('');
  if(els.charger)els.charger.innerHTML='<option value="all">All chargers</option>'+chargers.map(c=>`<option value="${esc(c.id)}">${esc(c.id)} · ${esc(c.type)} ${esc(c.power)} kW</option>`).join('');
}
function renderKpis(m){
  $('report-energy').textContent=`${num(m.energy,1)} kWh`;$('report-cost').textContent=money(m.cost);$('report-cost-kwh').textContent=m.energy?`${num(m.costKwh,1)} AMD`:'—';$('report-readiness').textContent=pct(m.readiness);$('report-utilization').textContent=pct(m.utilization);$('report-failure-rate').textContent=pct(m.sessions.length?m.failed/m.sessions.length*100:0);
  $('report-bay-utilization').textContent=pct(m.bayUtilization);$('report-no-show-rate').textContent=pct(m.reservationCounts.total?m.reservationCounts.noShow/m.reservationCounts.total*100:0);
  $('report-energy-note').textContent=`${num(m.sessionEnergy,1)} kWh depot · ${num(m.homeEnergy,1)} kWh home`;$('report-cost-note').textContent=`${money(m.sessionCost)} depot · ${money(m.homeCost)} home`;$('report-readiness-note').textContent=`${m.departures.length} dated departure outcome${m.departures.length===1?'':'s'}`;$('report-failure-note').textContent=`${m.failed} failed of ${m.sessions.length} sessions`;$('report-bay-note').textContent=`${m.parkingUsage.length} bay-day records`;$('report-no-show-note').textContent=`${m.reservationCounts.noShow} no-show · ${m.reservationCounts.cancelled} cancelled`;
}
function renderTrend(m){
  const vals=m.trend.map(x=>trendMode==='energy'?x.energy:x.cost),max=Math.max(1,...vals),total=vals.reduce((a,b)=>a+b,0);
  $('trend-total-label').textContent=trendMode==='energy'?'Total energy':'Total charging cost';$('trend-total').textContent=trendMode==='energy'?`${num(total,1)} kWh`:money(total);$('trend-peak').textContent=trendMode==='energy'?`${num(Math.max(0,...vals),1)} kWh`:money(Math.max(0,...vals));$('trend-average').textContent=trendMode==='energy'?`${num(total/Math.max(1,vals.length),1)} kWh`:money(total/Math.max(1,vals.length));
  $('report-trend-chart').innerHTML=m.trend.map((point,i)=>{const v=vals[i],height=v<=0?2:Math.max(6,Math.round(v/max*100)),tip=trendMode==='energy'?`${num(v,1)} kWh`:money(v);return `<div class="report-trend-point" title="${esc(tip)} · ${point.sessions} sessions"><div class="report-trend-bar-wrap"><span class="report-trend-bar ${trendMode==='cost'?'is-cost':''}" style="height:${height}%"></span></div><strong>${esc(point.label)}</strong><small>${trendMode==='energy'?num(v,0):num(v/1000,1)+'k'}</small></div>`}).join('');
}
function renderReadiness(m){
  const counts={ready:0,'missed-target':0,late:0,'at-risk':0};m.departures.forEach(x=>{counts[x.result]=(counts[x.result]||0)+1});const score=Math.max(0,Math.min(100,Math.round(m.readiness)||0));$('report-readiness-ring-value').textContent=`${score}%`;
  $('report-readiness-breakdown').innerHTML=[['Ready',counts.ready||0,'ready'],['Missed target',counts['missed-target']||0,'risk'],['Late',counts.late||0,'queued'],['At risk',counts['at-risk']||0,'charging']].map(([label,count,cls])=>`<div><span><i class="mini-dot dot-${cls}"></i>${label}</span><strong>${count}</strong></div>`).join('');
  const attention=m.departures.filter(x=>x.result!=='ready');$('report-risk-text').textContent=attention.length?`${attention.length} departure outcome${attention.length===1?'':'s'} missed SLA or need attention in this period.`:'No departure SLA misses in the selected period.';$('report-risk-callout').classList.toggle('ui-callout--warning',attention.length>0);$('report-risk-callout').classList.toggle('ui-callout--info',attention.length===0);
}
function renderDepartmentCost(m){const buckets={};m.sessions.forEach(x=>{const d=departmentForVehicle(x.vehicle);buckets[d]=(buckets[d]||0)+(Number(x.cost)||0)});m.reimbursements.forEach(x=>{const d=departmentForVehicle(x.vehicle);buckets[d]=(buckets[d]||0)+(Number(x.amount)||0)});const entries=Object.entries(buckets).sort((a,b)=>b[1]-a[1]),max=entries.length?Math.max(...entries.map(x=>x[1]),1):1;$('department-cost-bars').innerHTML=entries.length?entries.map(([name,value])=>`<div class="metric-bar-row"><div><span>${esc(name)}</span><strong>${money(value)}</strong></div><div class="ui-progress"><span class="ui-progress__bar" style="width:${Math.round(value/max*100)}%"></span></div></div>`).join(''):'<div class="reports-empty">No dated department cost records for this period.</div>'}
function renderStatusMix(m){const config=[['ready','Ready'],['charging','Charging'],['queued','Waiting'],['risk','At risk']];$('report-status-grid').innerHTML=config.map(([st,label])=>{const count=m.vehicles.filter(v=>v.status===st).length,p=m.vehicles.length?Math.round(count/m.vehicles.length*100):0;return `<div class="report-status-card report-status-card--${st}"><span>${label}</span><strong>${count}</strong><small>${p}% of selected fleet now</small></div>`}).join('')}
function vehicleStats(v,m){const sessions=m.sessions.filter(x=>x.vehicle===v.id),energy=sessions.reduce((a,x)=>a+(Number(x.energy)||0),0),cost=sessions.reduce((a,x)=>a+(Number(x.cost)||0),0),dep=m.departures.filter(x=>x.vehicle===v.id),missed=dep.filter(x=>x.result!=='ready').length;const readiness=dep.length?(missed?'At risk':'Ready'):(v.status==='risk'?'At risk':v.status==='charging'?'Charging':v.status==='ready'?'Ready':'Waiting');return {sessions,energy,cost,departures:dep,readiness}}
function renderVehicleTable(m){const rows=m.vehicles.slice(0,MAX_RENDER_ROWS);$('vehicle-report-count').textContent=`${m.vehicles.length} vehicle${m.vehicles.length===1?'':'s'}`;const html=rows.map(v=>{const d=driverForVehicle(v.id),stat=vehicleStats(v,m),cls=stat.readiness==='At risk'?'risk':stat.readiness==='Ready'?'ready':stat.readiness==='Charging'?'charging':'queued';return `<tr data-report-vehicle="${esc(v.id)}"><td><div class="entity-main"><strong>${esc(v.id)}</strong><span>${esc(v.name)}</span></div></td><td><div class="entity-main"><strong>${esc(d?.name||'Unassigned')}</strong><span>${esc(departmentForVehicle(v.id))}</span></div></td><td>${stat.sessions.length}</td><td>${num(stat.energy,1)} kWh</td><td>${money(stat.cost)}</td><td><div class="report-soc"><strong>${v.battery}%</strong><div class="ui-progress"><span class="ui-progress__bar" style="width:${Math.min(100,Number(v.battery)||0)}%"></span></div></div></td><td><span class="ui-pill status-pill status-${cls}">${stat.readiness}</span></td><td><span class="ui-pill status-pill status-${esc(v.status)}">${esc(statusLabel(v.status))}</span></td><td><button class="ui-row-menu" type="button" data-report-vehicle-open="${esc(v.id)}">•••</button></td></tr>`}).join('');els.vehicleRows.innerHTML=html||'<tr><td colspan="9"><div class="reports-empty">No vehicles match the current filters.</div></td></tr>';document.querySelectorAll('[data-report-vehicle-open]').forEach(btn=>btn.addEventListener('click',e=>{e.stopPropagation();openVehicleDrawer(btn.dataset.reportVehicleOpen)}));document.querySelectorAll('[data-report-vehicle]').forEach(row=>row.addEventListener('dblclick',()=>openVehicleDrawer(row.dataset.reportVehicle)))}
function renderChargerTable(m){const html=m.chargers.slice(0,MAX_RENDER_ROWS).map(c=>{const stat=chargerReportStats(m,c.id);return `<tr><td><div class="entity-main"><strong>${esc(c.id)}</strong><span>${esc(c.type)} · ${esc(c.power)} kW · Bay ${esc(c.bay)}</span></div></td><td><span class="ui-pill status-pill status-${esc(c.status)}">${esc(statusLabel(c.status))}</span></td><td>${stat.sessions.length}</td><td>${num(stat.energy,1)} kWh</td><td><div class="report-util-cell"><strong>${pct(stat.utilization)}</strong><div class="ui-progress"><span class="ui-progress__bar" style="width:${Math.min(100,stat.utilization)}%"></span></div></div></td><td><span class="report-health ${c.health<70?'is-low':c.health<90?'is-warning':''}">${c.health}%</span></td><td><button class="ui-row-menu" type="button" data-report-charger="${esc(c.id)}">•••</button></td></tr>`}).join('');els.chargerRows.innerHTML=html||'<tr><td colspan="7"><div class="reports-empty">No charger data matches the current filters.</div></td></tr>';document.querySelectorAll('[data-report-charger]').forEach(btn=>btn.addEventListener('click',()=>location.href=`./depot.html?charger=${encodeURIComponent(btn.dataset.reportCharger)}`))}
function renderHomeCharging(m){const claims=m.reimbursements,energy=claims.reduce((a,x)=>a+(Number(x.energy)||0),0),amount=claims.reduce((a,x)=>a+(Number(x.amount)||0),0),approved=claims.filter(x=>x.status==='approved').length;$('report-home-summary').innerHTML=`<div><span>Home energy</span><strong>${num(energy,1)} kWh</strong></div><div><span>Reimbursement</span><strong>${money(amount)}</strong></div><div><span>Approved claims</span><strong>${approved}/${claims.length}</strong></div>`;const by={};claims.forEach(x=>{const dep=departmentForVehicle(x.vehicle);if(!by[dep])by[dep]={energy:0,amount:0,count:0};by[dep].energy+=Number(x.energy)||0;by[dep].amount+=Number(x.amount)||0;by[dep].count++});$('report-home-list').innerHTML=Object.entries(by).map(([dep,v])=>`<div class="report-home-row"><div><strong>${esc(dep)}</strong><span>${v.count} claim${v.count===1?'':'s'} · ${num(v.energy,1)} kWh</span></div><strong>${money(v.amount)}</strong></div>`).join('')||'<div class="reports-empty">No home charging claims in this date range.</div>'}
function renderDepartures(m){const rows=m.departures.slice().sort((a,b)=>String(b.date).localeCompare(String(a.date))).slice(0,MAX_RENDER_ROWS);els.scheduleRows.innerHTML=rows.map(x=>{const v=vehicleById.get(x.vehicle),d=driverById.get(x.driver),label=x.result==='ready'?'Ready':x.result==='missed-target'?'Missed target':x.result==='late'?'Late':'At risk',cls=x.result==='ready'?'ready':'risk';return `<tr><td>${esc(formatDate(x.date))}</td><td><div class="entity-main"><strong>${esc(x.vehicle)}</strong><span>${esc(v?.name||'Vehicle')}</span></div></td><td>${esc(d?.name||'Unassigned')}</td><td>${esc(x.route||v?.route||'—')}</td><td>${esc(x.departure||'—')}</td><td>${num(x.targetSoc,0)}%</td><td>${num(x.actualSoc,0)}%</td><td><span class="ui-pill status-pill status-${cls}">${label}</span></td></tr>`}).join('')||'<tr><td colspan="8"><div class="reports-empty">No departure outcomes in this period.</div></td></tr>'}
function renderReservations(m){const c=m.reservationCounts,total=Math.max(1,c.total);$('report-reservation-summary').innerHTML=[['Total',c.total,'info'],['Completed',c.completed,'ready'],['Cancelled',c.cancelled,'queued'],['No-show',c.noShow,'risk'],['Expired',c.expired,'planned'],['Active / confirmed',c.active+c.confirmed,'charging']].map(([label,count,cls])=>`<div class="report-status-card report-status-card--${cls}"><span>${label}</span><strong>${count}</strong><small>${c.total?Math.round(count/total*100):0}% of reservations</small></div>`).join('');
  const allowedBays=new Set(m.parkingUsage.map(x=>x.parkingBayId));const bays=parkingBays.filter(b=>allowedBays.has(b.id));$('report-bay-rows').innerHTML=bays.slice(0,MAX_RENDER_ROWS).map(b=>{const stat=parkingBayReportStats(m,b.id);return `<tr><td><div class="entity-main"><strong>${esc(b.code)}</strong><span>${esc(b.type)}${b.accessible?' · Accessible':''}</span></div></td><td>${b.chargerId?esc(b.chargerId):'Parking only'}</td><td>${pct(stat.utilization)}</td><td>${num(stat.usedMinutes/60,1)} h</td><td>${num(stat.blockedMinutes/60,1)} h</td></tr>`}).join('')||'<tr><td colspan="5"><div class="reports-empty">No parking-bay history for the selected scope.</div></td></tr>'}
function renderActivityAndMaintenance(m){const slots=Array.from({length:8},(_,i)=>({start:6+i*2,count:0,energy:0}));m.sessions.forEach(x=>{const h=Number(String(x.start||'0').split(':')[0])||0;const slot=slots.find(row=>h>=row.start&&h<row.start+2);if(slot){slot.count++;slot.energy+=Number(x.energy)||0}});const max=Math.max(1,...slots.map(x=>x.count));$('report-activity-hours').innerHTML=slots.map(x=>`<div class="metric-bar-row"><div><span>${String(x.start).padStart(2,'0')}:00–${String(x.start+2).padStart(2,'0')}:00</span><strong>${x.count} sessions · ${num(x.energy,1)} kWh</strong></div><div class="ui-progress"><span class="ui-progress__bar" style="width:${Math.round(x.count/max*100)}%"></span></div></div>`).join('');$('report-busy-period').textContent=`Busiest: ${timeSlot(m.busySlot)} · ${m.busySlot?.count||0} sessions`;$('report-inactive-period').textContent=`Quietest: ${timeSlot(m.inactiveSlot)} · ${m.inactiveSlot?.count||0} sessions`;
  $('report-maintenance-summary').innerHTML=`<div><span>Tickets opened</span><strong>${m.maintenance.length}</strong></div><div><span>Resolved</span><strong>${m.resolvedMaintenance.length}</strong></div><div><span>Avg repair time</span><strong>${m.resolvedMaintenance.length?`${num(m.avgRepair,0)} min`:'—'}</strong></div><div><span>Repeated failures</span><strong>${m.repeatMaintenance.length}</strong></div>`;$('report-maintenance-list').innerHTML=m.maintenance.slice().sort((a,b)=>String(b.openedDate).localeCompare(String(a.openedDate))).slice(0,6).map(t=>`<div class="report-home-row"><div><strong>${esc(t.id)} · ${esc(t.chargerId)}</strong><span>${esc(formatDate(t.openedDate))} · ${esc(t.category)}</span></div><span class="ui-pill status-pill status-${t.status==='resolved'?'ready':'risk'}">${esc(t.status)}</span></div>`).join('')||'<div class="reports-empty">No maintenance tickets opened in this period.</div>'}
function renderSustainability(m){$('report-renewable').textContent=`${num(m.renewableKwh,1)} kWh`;$('report-grid-energy').textContent=`${num(m.gridKwh,1)} kWh`;$('report-renewable-share').textContent=pct(m.renewableShare);$('report-carbon').textContent=`${num(m.carbonAvoidedKg,1)} kg`;$('report-energy-mix-bar').style.width=`${Math.min(100,m.renewableShare)}%`;$('report-sustainability-note').textContent=`Based on ${m.energyHistory.length} dated depot-energy records. Carbon avoided is stored prototype telemetry, not a live external emissions calculation.`}
function updateFilterSummary(m){const parts=[`${formatDate(m.range.start)} – ${formatDate(m.range.end)}`];if(els.department.value!=='all')parts.push(departmentName(s,els.department.value));if(els.vehicle.value!=='all')parts.push(els.vehicle.value);if(els.driver.value!=='all')parts.push(driverById.get(els.driver.value)?.name||els.driver.value);if(els.charger.value!=='all')parts.push(els.charger.value);$('report-filter-summary').textContent=`${m.sessions.length} sessions · ${m.reservations.length} reservations · ${parts.join(' · ')}`}
function renderNow(){if(renderBusy){renderQueued=true;return}renderBusy=true;try{const m=report();renderKpis(m);renderTrend(m);renderReadiness(m);renderDepartmentCost(m);renderStatusMix(m);renderVehicleTable(m);renderChargerTable(m);renderHomeCharging(m);renderDepartures(m);renderReservations(m);renderActivityAndMaintenance(m);renderSustainability(m);updateFilterSummary(m)}catch(error){console.error('[VoltDrive Reports] Render failed',error);$('report-filter-summary').textContent='Report rendering failed. Check the browser console.'}finally{renderBusy=false;if(renderQueued){renderQueued=false;requestAnimationFrame(renderNow)}}}
function scheduleRender(){if(renderQueued)return;renderQueued=true;requestAnimationFrame(()=>{renderQueued=false;renderNow()})}
function openVehicleDrawer(vehicleId){const v=vehicleById.get(vehicleId);if(!v)return;const m=report(),d=driverForVehicle(v.id),stat=vehicleStats(v,m);drawerEntity=v.id;$('report-drawer-kicker').textContent='Vehicle analytics';$('report-drawer-title').textContent=`${v.id} · ${v.name}`;$('report-drawer-subtitle').textContent=`${v.route} · ${departmentForVehicle(v.id)} · ${formatDate(m.range.start)}–${formatDate(m.range.end)}`;$('report-drawer-body').innerHTML=`<section class="ui-detail-section"><div class="report-drawer-kpis"><div><span>Energy</span><strong>${num(stat.energy,1)} kWh</strong></div><div><span>Charging cost</span><strong>${money(stat.cost)}</strong></div><div><span>Sessions</span><strong>${stat.sessions.length}</strong></div><div><span>Departure outcomes</span><strong>${stat.departures.length}</strong></div></div></section><section class="ui-detail-section"><h3>Current readiness</h3><div class="ui-detail-grid"><div><span>Status</span><strong><span class="ui-pill status-pill status-${esc(v.status)}">${esc(statusLabel(v.status))}</span></strong></div><div><span>Target SOC</span><strong>${v.target}%</strong></div><div><span>Current SOC</span><strong>${v.battery}%</strong></div><div><span>Required energy</span><strong>${num(v.requiredKwh,1)} kWh</strong></div></div></section><section class="ui-detail-section"><h3>Assignment</h3><div class="ui-detail-list"><div><span>Driver</span><strong>${esc(d?.name||'Unassigned')}</strong></div><div><span>Department</span><strong>${esc(departmentForVehicle(v.id))}</strong></div><div><span>Route</span><strong>${esc(v.route)}</strong></div><div><span>Charger</span><strong>${esc(v.charger||'—')}</strong></div></div></section><section class="ui-detail-section"><h3>Dated charging activity</h3><div class="report-drawer-session-list">${stat.sessions.length?stat.sessions.slice(0,50).map(x=>`<div><div><strong>${esc(x.id)}</strong><span>${esc(formatDate(x.date))} · ${esc(x.charger)} · ${esc(x.duration)}</span></div><div><strong>${num(Number(x.energy)||0,1)} kWh</strong><span>${money(Number(x.cost)||0)}</span></div></div>`).join(''):'<div class="reports-empty">No sessions in this reporting period.</div>'}</div></section>`;els.backdrop.hidden=false;requestAnimationFrame(()=>{els.drawer.classList.add('is-open');els.backdrop.classList.add('is-visible');els.drawer.setAttribute('aria-hidden','false')})}
function closeDrawer(){els.drawer.classList.remove('is-open');els.backdrop.classList.remove('is-visible');els.drawer.setAttribute('aria-hidden','true');drawerEntity=null;setTimeout(()=>{els.backdrop.hidden=true},180)}
function toast(message){els.toast.textContent=message;els.toast.classList.add('is-visible');clearTimeout(toast.timer);toast.timer=setTimeout(()=>els.toast.classList.remove('is-visible'),2600)}
function exportCsv(){const m=report(),rows=[['VoltDrive Fleet Report',`${m.range.start} to ${m.range.end}`],['Energy kWh',m.energy.toFixed(1)],['Cost AMD',Math.round(m.cost)],['Readiness %',m.readiness.toFixed(1)],['Charger utilization %',m.utilization.toFixed(1)],['Bay utilization %',m.bayUtilization.toFixed(1)],['No-show reservations',m.reservationCounts.noShow],[],['Vehicle','Driver','Department','Route','Sessions','Energy kWh','Cost AMD','SOC %','Target %','Status']];m.vehicles.forEach(v=>{const d=driverForVehicle(v.id),stat=vehicleStats(v,m);rows.push([v.id,d?.name||'',departmentForVehicle(v.id),v.route,stat.sessions.length,stat.energy.toFixed(1),Math.round(stat.cost),v.battery,v.target,statusLabel(v.status)])});const csv=rows.map(row=>row.map(cell=>`"${String(cell??'').replace(/"/g,'""')}"`).join(',')).join('\n'),blob=new Blob([csv],{type:'text/csv;charset=utf-8'}),url=URL.createObjectURL(blob),a=document.createElement('a');a.href=url;a.download=`voltdrive-fleet-report-${els.period.value}.csv`;a.click();URL.revokeObjectURL(url);toast('Dated fleet report exported.')}
function resetFilters(){els.period.value='week';els.department.value='all';els.vehicle.value='all';els.driver.value='all';els.charger.value='all';scheduleRender();toast('Report filters reset.')}
[els.period,els.department,els.vehicle,els.driver,els.charger].forEach(el=>el?.addEventListener('change',scheduleRender));$('trend-tabs')?.addEventListener('click',e=>{const btn=e.target.closest('[data-trend]');if(!btn)return;trendMode=btn.dataset.trend;document.querySelectorAll('#trend-tabs .ui-tab').forEach(x=>x.classList.toggle('is-active',x===btn));renderTrend(report())});$('report-export')?.addEventListener('click',exportCsv);$('report-reset')?.addEventListener('click',resetFilters);$('open-schedules')?.addEventListener('click',()=>location.href='./schedules.html');$('report-drawer-close')?.addEventListener('click',closeDrawer);els.backdrop?.addEventListener('click',closeDrawer);$('report-drawer-primary')?.addEventListener('click',()=>{if(drawerEntity)location.href=`./vehicles.html?vehicle=${encodeURIComponent(drawerEntity)}`});$('report-drawer-secondary')?.addEventListener('click',()=>{if(drawerEntity)location.href=`./sessions.html?vehicle=${encodeURIComponent(drawerEntity)}`});document.addEventListener('keydown',e=>{if(e.key==='Escape'&&els.drawer?.classList.contains('is-open'))closeDrawer()});
populateFilters();renderNow();
}
