import {loadState,saveState,statusLabel} from '../core/fleet-state.js';
import {initCommon} from '../layout/common.js';
initCommon();
let s=loadState();
let activeId=null,editId=null,toastTimer=null;
const $=id=>document.getElementById(id);
const els={rows:$('schedule-rows'),q:$('schedule-search'),filter:$('schedule-filter'),sort:$('schedule-sort'),drawer:$('schedule-drawer'),backdrop:$('schedule-drawer-backdrop'),body:$('schedule-drawer-body'),dialog:$('schedule-form-dialog'),toast:$('schedule-toast')};
function normalize(){s.schedules=s.schedules.map((x,i)=>({driver:s.drivers.find(d=>d.vehicle===x.vehicle)?.id||'',requiredKwh:s.vehicles.find(v=>v.id===x.vehicle)?.requiredKwh||20,recurrence:'once',...x}));saveState(s)}
normalize();
const vehicle=id=>s.vehicles.find(v=>v.id===id),driver=id=>s.drivers.find(d=>d.id===id);
function mins(t){const [h,m]=(t||'00:00').split(':').map(Number);return h*60+m}
function fmt(n){n=(n+1440)%1440;return `${String(Math.floor(n/60)).padStart(2,'0')}:${String(n%60).padStart(2,'0')}`}
function readiness(x){const v=vehicle(x.vehicle);if(!v)return{label:'Vehicle missing',ok:false};if(v.battery>=x.target||v.status==='ready')return{label:'Ready now',ok:true};if(v.status==='risk')return{label:fmt(mins(x.departure)+12),ok:false};if(v.status==='queued'||!v.power)return{label:'Awaiting charger',ok:x.status!=='risk'};return{label:fmt(mins(x.departure)-Math.max(5,s.settings.departureBuffer||20)),ok:true}}
function overlap(a,b){if(a.id===b.id)return false;const dep=mins(a.departure),ret=mins(a.return),dep2=mins(b.departure),ret2=mins(b.return);return dep<ret2&&dep2<ret}
function conflictFor(x){return s.schedules.some(o=>overlap(x,o)&&(o.vehicle===x.vehicle||(x.driver&&o.driver===x.driver)))}
function computedStatus(x){const v=vehicle(x.vehicle);if(conflictFor(x))return'conflict';if(!v)return'conflict';if(x.status==='risk'||v.status==='risk')return'risk';return x.status==='confirmed'?'confirmed':'planned'}
function label(st){return st==='risk'?'At risk':st[0].toUpperCase()+st.slice(1)}
function render(){const q=els.q.value.trim().toLowerCase();let data=s.schedules.map(x=>({...x,computed:computedStatus(x)})).filter(x=>{const v=vehicle(x.vehicle),d=driver(x.driver);return (!q||[x.id,x.route,x.vehicle,v?.name,d?.name].join(' ').toLowerCase().includes(q))&&(els.filter.value==='all'||x.computed===els.filter.value)});if(els.sort.value==='risk'){const r={conflict:0,risk:1,planned:2,confirmed:3};data.sort((a,b)=>r[a.computed]-r[b.computed]||a.departure.localeCompare(b.departure))}else if(els.sort.value==='soc')data.sort((a,b)=>(vehicle(a.vehicle)?.battery||0)-(vehicle(b.vehicle)?.battery||0));else data.sort((a,b)=>a.departure.localeCompare(b.departure));$('schedule-total').textContent=s.schedules.length;$('schedule-confirmed').textContent=s.schedules.filter(x=>computedStatus(x)==='confirmed').length;$('schedule-risk').textContent=s.schedules.filter(x=>computedStatus(x)==='risk').length;$('schedule-conflicts').textContent=s.schedules.filter(x=>computedStatus(x)==='conflict').length;$('schedule-buffer').textContent=`${s.settings.departureBuffer} min buffer`;els.rows.innerHTML=data.map(x=>{const v=vehicle(x.vehicle),d=driver(x.driver),ready=readiness(x),pct=v?Math.min(100,Math.round(v.battery/Math.max(1,x.target)*100)):0;return `<tr class="schedule-table-row ${x.computed==='risk'||x.computed==='conflict'?'row-risk':''}" data-schedule-row="${x.id}"><td><div class="schedule-time-cell"><strong>${x.departure}</strong><span>${x.id}</span></div></td><td><div class="entity-main"><strong>${x.route}</strong><span>${x.recurrence==='once'?'One time':x.recurrence}</span></div></td><td><div class="entity-main"><strong>${x.vehicle} · ${v?.name||'Unknown vehicle'}</strong><span>${d?.name||'Driver unassigned'}</span></div></td><td><div class="schedule-soc"><div><strong>${v?.battery??'—'}%</strong><span>Target ${x.target}%</span></div><div class="mini-progress"><i style="width:${pct}%"></i></div><small>${x.requiredKwh||v?.requiredKwh||0} kWh required</small></div></td><td><div class="entity-main"><strong>${ready.label}</strong><span>${ready.ok?'Within plan':'Needs attention'}</span></div></td><td><div class="entity-main"><strong>${x.return}</strong><span>${Math.max(0,mins(x.return)-mins(x.departure))} min route</span></div></td><td><span class="ui-pill status-pill status-${x.computed}">${label(x.computed)}</span></td><td><button class="ui-row-menu" type="button" data-open-schedule="${x.id}">•••</button></td></tr>`}).join('')||'<tr><td colspan="8"><div class="ops-empty">No schedules match these filters.</div></td></tr>';document.querySelectorAll('[data-open-schedule]').forEach(b=>b.onclick=e=>{e.stopPropagation();openDrawer(b.dataset.openSchedule)});document.querySelectorAll('[data-schedule-row]').forEach(r=>r.ondblclick=()=>openDrawer(r.dataset.scheduleRow))}
function openDrawer(id){const x=s.schedules.find(v=>v.id===id);if(!x)return;activeId=id;const v=vehicle(x.vehicle),d=driver(x.driver),st=computedStatus(x),ready=readiness(x),hasConflict=conflictFor(x);$('schedule-drawer-title').textContent=x.route;$('schedule-drawer-subtitle').textContent=`${x.id} · ${x.departure} departure`;els.body.innerHTML=`${st==='risk'?'<div class="ui-callout ui-callout--warning"><strong>Readiness risk</strong><span>The current charging plan may not deliver the required SOC before the departure buffer.</span></div>':''}${hasConflict?'<div class="ui-callout ui-callout--danger"><strong>Schedule conflict</strong><span>The selected vehicle or driver overlaps another route.</span></div>':''}<section class="schedule-detail-hero"><div><span>Departure</span><strong>${x.departure}</strong><small>Return ${x.return}</small></div><span class="ui-pill status-pill status-${st}">${label(st)}</span></section><section class="ui-detail-section"><h3>Assignment</h3><div class="ui-detail-list"><div><span>Route</span><strong>${x.route}</strong></div><div><span>Vehicle</span><strong>${x.vehicle} · ${v?.name||'Unknown'}</strong></div><div><span>Driver</span><strong>${d?.name||'Unassigned'}</strong></div><div><span>Recurrence</span><strong>${x.recurrence}</strong></div></div></section><section class="ui-detail-section"><h3>Charging readiness</h3><div class="ui-detail-grid"><div><span>Current SOC</span><strong>${v?.battery??'—'}%</strong></div><div><span>Required SOC</span><strong>${x.target}%</strong></div><div><span>Required energy</span><strong>${x.requiredKwh||v?.requiredKwh||0} kWh</strong></div><div><span>Ready ETA</span><strong>${ready.label}</strong></div><div><span>Assigned charger</span><strong>${v?.charger||'—'}</strong></div><div><span>Charging power</span><strong>${v?.power||0} kW</strong></div></div></section><section class="ui-detail-section"><h3>Planning policy</h3><div class="ui-detail-list"><div><span>Departure buffer</span><strong>${s.settings.departureBuffer} min</strong></div><div><span>Priority</span><strong>${v?.priority||'normal'}</strong></div><div><span>Current vehicle status</span><strong>${v?statusLabel(v.status):'—'}</strong></div></div></section>`;$('schedule-confirm').textContent=x.status==='confirmed'?'Return to planned':'Confirm departure';els.backdrop.hidden=false;requestAnimationFrame(()=>els.backdrop.classList.add('is-visible'));els.drawer.classList.add('is-open');els.drawer.setAttribute('aria-hidden','false')}
function closeDrawer(){els.drawer.classList.remove('is-open');els.drawer.setAttribute('aria-hidden','true');els.backdrop.classList.remove('is-visible');setTimeout(()=>els.backdrop.hidden=true,180)}
function fillSelects(x){$('schedule-form-vehicle').innerHTML=s.vehicles.map(v=>`<option value="${v.id}">${v.id} · ${v.name}</option>`).join('');$('schedule-form-driver').innerHTML='<option value="">Unassigned</option>'+s.drivers.filter(d=>d.status!=='suspended').map(d=>`<option value="${d.id}">${d.name} · ${d.department}</option>`).join('');$('schedule-form-vehicle').value=x?.vehicle||s.vehicles[0]?.id||'';$('schedule-form-driver').value=x?.driver||s.drivers.find(d=>d.vehicle===$('schedule-form-vehicle').value)?.id||''}
function openForm(id=null){editId=id;const x=id?s.schedules.find(v=>v.id===id):null;$('schedule-form-title').textContent=x?'Edit schedule':'New schedule';fillSelects(x);$('schedule-form-route').value=x?.route||'';$('schedule-form-departure').value=x?.departure||'09:00';$('schedule-form-return').value=x?.return||'12:00';$('schedule-form-target').value=x?.target||85;$('schedule-form-energy').value=x?.requiredKwh||20;$('schedule-form-recurrence').value=x?.recurrence||'once';$('schedule-form-warning').hidden=true;els.dialog.showModal()}
function draftFromForm(){return{id:editId||'DRAFT',vehicle:$('schedule-form-vehicle').value,driver:$('schedule-form-driver').value,route:$('schedule-form-route').value.trim(),departure:$('schedule-form-departure').value,return:$('schedule-form-return').value,target:Number($('schedule-form-target').value)||85,requiredKwh:Number($('schedule-form-energy').value)||0,recurrence:$('schedule-form-recurrence').value,status:'planned'}}
function validateDraft(x){const conflicts=s.schedules.filter(o=>o.id!==editId&&overlap(x,o)&&(o.vehicle===x.vehicle||(x.driver&&o.driver===x.driver)));const invalidTime=mins(x.return)<=mins(x.departure);$('schedule-form-warning').hidden=!conflicts.length&&!invalidTime;$('schedule-form-warning-text').textContent=invalidTime?'Return time must be later than departure.':conflicts.length?`Conflicts with ${conflicts.map(c=>c.id).join(', ')}.`:'';return !invalidTime}
function saveSchedule(){const data=draftFromForm();if(!validateDraft(data))return false;if(editId)Object.assign(s.schedules.find(x=>x.id===editId),data,{id:editId});else{const n=Math.max(0,...s.schedules.map(x=>Number((x.id.match(/\d+/)||['0'])[0])))+1;s.schedules.push({...data,id:`SCH-${String(n).padStart(2,'0')}`})}const v=vehicle(data.vehicle);if(v){v.route=data.route;v.departure=data.departure;v.target=data.target;v.requiredKwh=data.requiredKwh;const st=computedStatus(editId?s.schedules.find(x=>x.id===editId):s.schedules[s.schedules.length-1]);if(st==='risk')v.status='risk'}const d=driver(data.driver);if(d&&(!d.vehicle||d.vehicle==='—'))d.vehicle=data.vehicle;saveState(s);render();if(editId===activeId)openDrawer(activeId);toast(editId?'Schedule updated':'Schedule created');return true}
function toggleConfirm(){const x=s.schedules.find(v=>v.id===activeId);if(!x)return;x.status=x.status==='confirmed'?'planned':'confirmed';saveState(s);render();openDrawer(x.id);toast(x.status==='confirmed'?'Departure confirmed':'Departure returned to planned')}
function importCsv(file){const reader=new FileReader();reader.onload=()=>{const lines=String(reader.result).trim().split(/\r?\n/).filter(Boolean);let added=0;for(const line of lines.slice(1)){const [vehicleId,driverId,route,departure,ret,target]=line.split(',').map(v=>v.trim());if(!vehicle(vehicleId)||!route||!departure||!ret)continue;const n=Math.max(0,...s.schedules.map(x=>Number((x.id.match(/\d+/)||['0'])[0])))+1;s.schedules.push({id:`SCH-${String(n).padStart(2,'0')}`,vehicle:vehicleId,driver:driverId||'',route,departure,return:ret,target:Number(target)||85,requiredKwh:vehicle(vehicleId)?.requiredKwh||20,recurrence:'once',status:'planned'});added++}saveState(s);render();toast(`${added} schedule${added===1?'':'s'} imported`)};reader.readAsText(file)}
function toast(msg){clearTimeout(toastTimer);els.toast.textContent=msg;els.toast.classList.add('is-visible');toastTimer=setTimeout(()=>els.toast.classList.remove('is-visible'),2200)}
[els.q,els.filter,els.sort].forEach(el=>el.addEventListener('input',render));$('schedule-add').onclick=()=>openForm();$('schedule-import').onclick=()=>$('schedule-file').click();$('schedule-file').onchange=e=>{const f=e.target.files?.[0];if(f)importCsv(f);e.target.value=''};$('schedule-drawer-close').onclick=closeDrawer;els.backdrop.onclick=closeDrawer;$('schedule-edit').onclick=()=>openForm(activeId);$('schedule-open-vehicle').onclick=()=>{const x=s.schedules.find(v=>v.id===activeId);if(x)location.href=`./vehicles.html?vehicle=${encodeURIComponent(x.vehicle)}`};$('schedule-confirm').onclick=toggleConfirm;$('schedule-form-vehicle').onchange=()=>{const d=s.drivers.find(x=>x.vehicle===$('schedule-form-vehicle').value);if(d)$('schedule-form-driver').value=d.id;validateDraft(draftFromForm())};['schedule-form-driver','schedule-form-departure','schedule-form-return'].forEach(id=>$(id).addEventListener('change',()=>validateDraft(draftFromForm())));$('schedule-form').addEventListener('submit',e=>{if(e.submitter?.value==='cancel')return;if(!saveSchedule())e.preventDefault()});render();
