import {loadState,saveState,statusLabel} from '../core/fleet-state.js';
import {initCommon} from '../layout/common.js';
initCommon();
let s=loadState();
let activeVehicleId=null;
let editVehicleId=null;
const $=id=>document.getElementById(id);
const els={q:$('vehicle-search'),status:$('status-filter'),priority:$('priority-filter'),sort:$('vehicle-sort'),table:$('vehicle-table'),count:$('vehicle-count'),drawer:$('vehicle-drawer'),backdrop:$('vehicle-drawer-backdrop'),drawerBody:$('drawer-body'),dialog:$('vehicle-dialog'),driverDialog:$('driver-dialog'),toast:$('vehicle-toast')};
const summary={total:$('summary-total'),charging:$('summary-charging'),ready:$('summary-ready'),risk:$('summary-risk'),soc:$('summary-soc')};
const metaSeed={
 'AM-101':{manufacturer:'Mercedes-Benz',model:'eSprinter',vin:'W1V3EBHY8RT101001',capacity:81,connector:'CCS2',range:198,odometer:28410,group:'Delivery',ownership:'Fleet',plugCharge:'Enabled',energyMonth:612,costMonth:48420},
 'AM-102':{manufacturer:'Mercedes-Benz',model:'eSprinter',vin:'W1V3EBHY8RT102002',capacity:81,connector:'CCS2',range:312,odometer:26105,group:'Delivery',ownership:'Fleet',plugCharge:'Enabled',energyMonth:574,costMonth:44760},
 'AM-103':{manufacturer:'Ford',model:'E-Transit',vin:'WF0EXXTTGE103003',capacity:68,connector:'CCS2',range:226,odometer:31844,group:'Airport',ownership:'Fleet',plugCharge:'Enabled',energyMonth:701,costMonth:55210},
 'AM-104':{manufacturer:'Ford',model:'E-Transit',vin:'WF0EXXTTGE104004',capacity:68,connector:'CCS2',range:111,odometer:35670,group:'West Hub',ownership:'Fleet',plugCharge:'Enabled',energyMonth:746,costMonth:59180},
 'AM-105':{manufacturer:'Volkswagen',model:'ID. Buzz',vin:'WVWZZZEB5PH105005',capacity:77,connector:'CCS2',range:284,odometer:19422,group:'Shuttle',ownership:'Fleet',plugCharge:'Pending',energyMonth:438,costMonth:34700},
 'AM-106':{manufacturer:'Volkswagen',model:'ID. Buzz',vin:'WVWZZZEB5PH106006',capacity:77,connector:'CCS2',range:351,odometer:18304,group:'Shuttle',ownership:'Fleet',plugCharge:'Enabled',energyMonth:401,costMonth:31960},
 'AM-107':{manufacturer:'Hyundai',model:'IONIQ 5',vin:'KMHKR81CPPU107007',capacity:77,connector:'CCS2 + Type 2',range:296,odometer:14728,group:'Executive',ownership:'Fleet',plugCharge:'Enabled',energyMonth:329,costMonth:26610},
 'AM-108':{manufacturer:'Tesla',model:'Model Y',vin:'LRWYGCEK1PC108008',capacity:75,connector:'CCS2',range:171,odometer:22018,group:'Executive',ownership:'Fleet',plugCharge:'Enabled',energyMonth:365,costMonth:29140}
};
function ensureVehicleMeta(){s.vehicles.forEach((v,i)=>{const m=metaSeed[v.id]||{};v.manufacturer??=m.manufacturer||v.name.split(' ')[0]||'—';v.model??=m.model||v.name;v.vin??=m.vin||`VD-FLEET-${String(i+1).padStart(6,'0')}`;v.capacity??=m.capacity||75;v.connector??=m.connector||'CCS2';v.range??=m.range||Math.round(v.battery*3.7);v.odometer??=m.odometer||0;v.group??=m.group||'General';v.ownership??=m.ownership||'Fleet';v.plugCharge??=m.plugCharge||'Enabled';v.energyMonth??=m.energyMonth||0;v.costMonth??=m.costMonth||0;v.active??=true;});saveState(s)}
ensureVehicleMeta();
const money=n=>`${Number(n||0).toLocaleString('en-US')} AMD`;
function driverFor(v){return s.drivers.find(d=>d.vehicle===v.id)||null}
function readyEta(v){if(v.status==='ready')return 'Ready now';if(!v.power)return 'Waiting';const hours=Math.max(0,v.requiredKwh||0)/Math.max(1,v.power);const mins=Math.round(hours*60);return mins<60?`${mins} min`:`${Math.floor(mins/60)}h ${mins%60}m`}
function historyFor(v){return [
 {date:'Aug 13',charger:v.charger==='—'?'DC-02':v.charger,energy:Math.max(18,Math.round((v.energyMonth||240)/12)),cost:Math.max(1400,Math.round((v.costMonth||21000)/12)),status:v.status==='risk'?'Interrupted':'Completed'},
 {date:'Aug 11',charger:'DC-02',energy:34,cost:2780,status:'Completed'},
 {date:'Aug 9',charger:'AC-07',energy:21,cost:1690,status:'Completed'}
]}
function updateSummary(){const active=s.vehicles.filter(v=>v.active!==false);summary.total.textContent=active.length;summary.charging.textContent=active.filter(v=>v.status==='charging').length;summary.ready.textContent=active.filter(v=>v.status==='ready').length;summary.risk.textContent=active.filter(v=>v.status==='risk').length;summary.soc.textContent=`${Math.round(active.reduce((a,v)=>a+v.battery,0)/Math.max(1,active.length))}%`}
function render(){updateSummary();const needle=els.q.value.trim().toLowerCase();let arr=s.vehicles.filter(v=>v.active!==false).filter(v=>{const d=driverFor(v);const hay=`${v.name} ${v.plate} ${v.route} ${v.group} ${d?d.name:''}`.toLowerCase();return (!needle||hay.includes(needle))&&(els.status.value==='all'||v.status===els.status.value)&&(els.priority.value==='all'||v.priority===els.priority.value)});if(els.sort.value==='soc')arr.sort((a,b)=>a.battery-b.battery);else if(els.sort.value==='name')arr.sort((a,b)=>a.name.localeCompare(b.name));else if(els.sort.value==='cost')arr.sort((a,b)=>b.costMonth-a.costMonth);else arr.sort((a,b)=>a.departure.localeCompare(b.departure));els.count.textContent=`${arr.length} vehicle${arr.length===1?'':'s'}`;els.table.innerHTML=arr.map(v=>{const d=driverFor(v);return `<tr class="${v.status==='risk'?'row-risk':''}" data-vehicle-row="${v.id}"><td><div class="vehicle-identity"><span class="vehicle-identity__icon">◇</span><div><strong>${v.name}</strong><span>${v.plate} · ${v.manufacturer} ${v.model}</span></div></div></td><td><div class="entity-main"><strong>${d?d.name:'Unassigned'}</strong><span>${v.group}</span></div></td><td><div class="vehicle-battery ${v.status==='risk'?'is-risk':''}"><div class="vehicle-battery__top"><strong>${v.battery}%</strong><span>Target ${v.target}%</span></div><div class="mini-progress"><i style="width:${Math.min(100,(v.battery/Math.max(1,v.target))*100)}%"></i></div><small>${readyEta(v)}</small></div></td><td><div class="departure-cell"><strong>${v.departure}</strong><span>${v.route}</span></div></td><td><div class="entity-main"><strong>${v.charger}</strong><span>${v.power?`${v.power} kW · ${v.connector}`:`${v.connector} · no power`}</span></div></td><td><div class="entity-main"><strong>${v.energyMonth} kWh</strong><span>${money(v.costMonth)}</span></div></td><td><span class="ui-pill status-pill status-${v.status}">${statusLabel(v.status)}</span></td><td><button class="ui-row-menu" type="button" data-open-vehicle="${v.id}" aria-label="Open ${v.name}">•••</button></td></tr>`}).join('')||'<tr><td colspan="8"><div class="ops-empty">No vehicles match these filters.</div></td></tr>';document.querySelectorAll('[data-open-vehicle]').forEach(btn=>btn.addEventListener('click',e=>{e.stopPropagation();openDrawer(btn.dataset.openVehicle)}));document.querySelectorAll('[data-vehicle-row]').forEach(row=>row.addEventListener('dblclick',()=>openDrawer(row.dataset.vehicleRow)))}
function openDrawer(id){const v=s.vehicles.find(x=>x.id===id);if(!v)return;activeVehicleId=id;const d=driverFor(v);$('drawer-title').textContent=v.name;$('drawer-subtitle').textContent=`${v.plate} · ${v.id} · ${statusLabel(v.status)}`;const hist=historyFor(v);els.drawerBody.innerHTML=`${v.status==='risk'?'<div class="ui-risk-banner"><strong>Departure readiness at risk</strong><span>This vehicle needs manager attention before its scheduled departure.</span></div>':''}<section class="vehicle-profile-hero"><div class="vehicle-profile-battery"><span>Current SOC</span><strong>${v.battery}%</strong><div class="mini-progress"><i style="width:${v.battery}%"></i></div><small>Target ${v.target}% · ${v.requiredKwh} kWh remaining</small></div><div class="vehicle-profile-status"><span class="ui-pill status-pill status-${v.status}">${statusLabel(v.status)}</span><strong>${readyEta(v)}</strong><small>estimated readiness</small></div></section><section class="ui-detail-section"><h3>Technical profile</h3><div class="ui-detail-grid"><div><span>Manufacturer / model</span><strong>${v.manufacturer} ${v.model}</strong></div><div><span>Battery capacity</span><strong>${v.capacity} kWh</strong></div><div><span>Connector</span><strong>${v.connector}</strong></div><div><span>Estimated range</span><strong>${v.range} km</strong></div><div><span>VIN</span><strong>${v.vin}</strong></div><div><span>Odometer</span><strong>${Number(v.odometer).toLocaleString()} km</strong></div></div></section><section class="ui-detail-section"><h3>Assignment & departure</h3><div class="ui-detail-list"><div><span>Driver</span><strong>${d?d.name:'Unassigned'}</strong></div><div><span>Department / group</span><strong>${v.group}</strong></div><div><span>Route</span><strong>${v.route}</strong></div><div><span>Next departure</span><strong>${v.departure}</strong></div><div><span>Assigned charger</span><strong>${v.charger}</strong></div><div><span>Priority</span><strong class="text-capitalize">${v.priority}</strong></div><div><span>Plug & Charge</span><strong>${v.plugCharge}</strong></div></div></section><section class="ui-detail-section"><h3>This month</h3><div class="ui-detail-grid"><div><span>Energy</span><strong>${v.energyMonth} kWh</strong></div><div><span>Charging cost</span><strong>${money(v.costMonth)}</strong></div></div></section><section class="ui-detail-section"><div class="vehicle-section-head"><h3>Recent charging</h3><a href="./sessions.html">All sessions</a></div><div class="vehicle-history">${hist.map(h=>`<div><span>${h.date}</span><strong>${h.charger}</strong><span>${h.energy} kWh</span><span>${money(h.cost)}</span><em class="${h.status==='Completed'?'is-ok':'is-warn'}">${h.status}</em></div>`).join('')}</div></section>`;els.backdrop.hidden=false;requestAnimationFrame(()=>els.backdrop.classList.add('is-visible'));els.drawer.classList.add('is-open');els.drawer.setAttribute('aria-hidden','false')}
function closeDrawer(){els.drawer.classList.remove('is-open');els.drawer.setAttribute('aria-hidden','true');els.backdrop.classList.remove('is-visible');setTimeout(()=>els.backdrop.hidden=true,180)}
function fillVehicleForm(v){$('form-name').value=v?.name||'';$('form-plate').value=v?.plate||'';$('form-manufacturer').value=v?.manufacturer||'';$('form-model').value=v?.model||'';$('form-vin').value=v?.vin||'';$('form-capacity').value=v?.capacity||75;$('form-connector').value=v?.connector||'CCS2';$('form-target').value=v?.target||s.settings.defaultTarget||85;$('form-route').value=v?.route||'';$('form-departure').value=v?.departure||'09:00'}
function openVehicleDialog(id=null){editVehicleId=id;const v=id?s.vehicles.find(x=>x.id===id):null;$('vehicle-dialog-title').textContent=v?'Edit vehicle':'Add vehicle';fillVehicleForm(v);els.dialog.showModal()}
function saveVehicleForm(){const existing=editVehicleId?s.vehicles.find(x=>x.id===editVehicleId):null;const data={name:$('form-name').value.trim(),plate:$('form-plate').value.trim(),manufacturer:$('form-manufacturer').value.trim()||'—',model:$('form-model').value.trim()||'—',vin:$('form-vin').value.trim()||'—',capacity:Number($('form-capacity').value)||75,connector:$('form-connector').value,target:Number($('form-target').value)||Number(s.settings.defaultTarget)||85,route:$('form-route').value.trim()||'Unassigned route',departure:$('form-departure').value||'09:00'};if(existing){Object.assign(existing,data)}else{const next=String(s.vehicles.length+1).padStart(3,'0');s.vehicles.push({id:`AM-${next}`,battery:50,requiredKwh:25,status:'queued',charger:'—',power:0,priority:'normal',range:185,odometer:0,group:'General',ownership:'Fleet',plugCharge:'Pending',energyMonth:0,costMonth:0,active:true,...data});}saveState(s);render();toast(existing?'Vehicle updated':'Vehicle added');if(existing&&activeVehicleId===existing.id)openDrawer(existing.id)}
function openDriverDialog(){const v=s.vehicles.find(x=>x.id===activeVehicleId);if(!v)return;const current=driverFor(v);$('driver-dialog-copy').textContent=`Assign a driver to ${v.name}.`;$('driver-choice-list').innerHTML=`<label class="driver-choice"><input type="radio" name="driver-choice" value="" ${current?'':'checked'}><div><strong>Unassigned</strong><span>No active driver</span></div></label>`+s.drivers.map(d=>`<label class="driver-choice"><input type="radio" name="driver-choice" value="${d.id}" ${current?.id===d.id?'checked':''}><div><strong>${d.name}</strong><span>${d.department} · ${d.shift}</span></div></label>`).join('');els.driverDialog.showModal()}
function assignDriver(){const choice=document.querySelector('input[name="driver-choice"]:checked');if(!choice)return;const v=s.vehicles.find(x=>x.id===activeVehicleId);if(!v)return;s.drivers.forEach(d=>{if(d.vehicle===v.id)d.vehicle='—'});if(choice.value){const d=s.drivers.find(x=>x.id===choice.value);if(d){const oldVehicle=d.vehicle;d.vehicle=v.id;if(oldVehicle&&oldVehicle!=='—'&&oldVehicle!==v.id){const old=s.vehicles.find(x=>x.id===oldVehicle);if(old)old.group=old.group||d.department}}}saveState(s);render();openDrawer(v.id);toast('Driver assignment updated')}
let toastTimer;function toast(msg){clearTimeout(toastTimer);els.toast.textContent=msg;els.toast.classList.add('is-visible');toastTimer=setTimeout(()=>els.toast.classList.remove('is-visible'),2200)}
[els.q,els.status,els.priority,els.sort].forEach(el=>el?.addEventListener('input',render));
$('add-vehicle')?.addEventListener('click',()=>openVehicleDialog());
$('simulate-button')?.addEventListener('click',()=>{s.vehicles.forEach(v=>{if(v.status==='charging'){v.battery=Math.min(v.target,v.battery+4);v.requiredKwh=Math.max(0,v.requiredKwh-3);v.range=Math.round(v.range+12);if(v.battery>=v.target){v.status='ready';v.power=0;v.charger='—'}}});saveState(s);render();if(activeVehicleId)openDrawer(activeVehicleId);toast('Fleet advanced by 10 minutes')});
$('drawer-close')?.addEventListener('click',closeDrawer);els.backdrop?.addEventListener('click',closeDrawer);$('drawer-edit')?.addEventListener('click',()=>openVehicleDialog(activeVehicleId));$('drawer-driver')?.addEventListener('click',openDriverDialog);$('drawer-operations')?.addEventListener('click',()=>{location.href=`./operations.html?vehicle=${encodeURIComponent(activeVehicleId||'')}`});
$('vehicle-form')?.addEventListener('submit',e=>{if(e.submitter?.value==='cancel')return;if(!$('form-name').value.trim()||!$('form-plate').value.trim()){e.preventDefault();return}saveVehicleForm()});
$('driver-form')?.addEventListener('submit',e=>{if(e.submitter?.value==='cancel')return;assignDriver()});
render();
const requestedVehicle=new URLSearchParams(location.search).get('vehicle');
if(requestedVehicle&&s.vehicles.some(v=>v.id===requestedVehicle))openDrawer(requestedVehicle);
